### ISSUE TITLE
Add an example .config file

### ISSUE THREAD

**Issue by rubyFeedback** [mpdrescher/web-radio#1]
Hey there,

It may be useful to add an example .config file with a few radio stations by default.
I had to fiddle for some minutes before I finally got a file that web-radio accepted. It
worked past that point but I think an example.config file or something like that
may be helpful to newcomers. Thanks for reading!

**Comment by mpdrescher** [comment]
Hi! Thank you for your suggestion. I just updated the default .config file with some stations.

To be fair, this is a minimal program I wrote as a beginner programmer.
As you have probably noticed it lacks the user-friendliness available in standard software such as VLC, which I switched to after some time using this.

I enjoyed getting your feedback and being reminded about this project nonetheless :)
